name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Release
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: artifacts/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
