name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Upload release artifacts
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: "artifacts/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
